server:
  port: 8081
spring:
  application:
    name: ${HOSTNAME:eureka-client}
eureka:
  client:
    preferSameZoneEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/
  instance:
    preferIpAddress: true
    metadataMap:
      zone: zone1
